import React,{useState,useEffect,useRef,memo} from 'react';
import data from './data.json';
const {pages,media}=data;
const route=()=>decodeURIComponent(location.pathname).replace(/^\/+|\/+$/g,'');
const initial=()=>pages[route()]&&pages[route()].id!==pages.homepage.id?[route()]:[];
const Markup=memo(({html})=><div dangerouslySetInnerHTML={{__html:html}}/>);
export default function App(){
 const [stack,setStack]=useState(initial),[slide,setSlide]=useState(0),[zoom,setZoom]=useState(null);const touch=useRef(null);
 const homePhotos=pages.homepage.photos;
 function navigate(path){const p=path.replace(/^\//,'');if(!pages[p])return;setZoom(null);setStack(s=>p==='index'||p==='information'?[p]:[...s.filter(x=>x!==p),p]);history.pushState({},'',`/${p}`)}
 function close(){if(zoom){setZoom(null);return}setStack(s=>{const next=s.slice(0,-1);history.pushState({},'',next.length?'/'+next.at(-1):'/');return next})}
 function move(n){if(zoom)setZoom(z=>({...z,index:(z.index+n+z.photos.length)%z.photos.length}));else setSlide(s=>(s+n+homePhotos.length)%homePhotos.length)}
 useEffect(()=>{const resize=()=>{const w=innerWidth,h=innerHeight,portrait=w/h<=.8,mobile=portrait||(w/h>=2/3&&h<=500),weight=(mobile&&!portrait?18:9)+5*Math.min(1,Math.max(0,h/w-1)/.777777778);document.documentElement.style.fontSize=`${Math.max(20,Math.min(w,h)*weight/100)*.16*(mobile?1.5:1)}px`;document.documentElement.classList.toggle('mobile',mobile)};resize();addEventListener('resize',resize);const pop=()=>{setStack(initial());setZoom(null)};addEventListener('popstate',pop);return()=>{removeEventListener('resize',resize);removeEventListener('popstate',pop)}},[]);
 useEffect(()=>{const key=e=>{if(e.key==='Escape')close();if((!stack.length||zoom)&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(e.key==='ArrowLeft'?-1:1)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[stack,zoom]);
 function delegate(e,p){const photo=e.target.closest('[data-photo]');if(photo){const photos=pages[p].photos;setZoom({photos,index:photos.indexOf(photo.dataset.photo)});return}const a=e.target.closest('a');if(!a)return;if(a.rel==='close-overlay'){e.preventDefault();close();return}const href=a.getAttribute('href');if(pages[href.replace(/^\//,'')]){e.preventDefault();navigate(href)}}
 const m=media[homePhotos[slide]];
 return <><div className="home" inert={stack.length?true:undefined}><header onClick={e=>delegate(e,'top-nav')}><Markup html={pages['top-nav'].html}/></header><main className="slideshow" aria-label="Photography slideshow" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current!==null&&Math.abs(e.changedTouches[0].clientX-touch.current)>30)move(e.changedTouches[0].clientX<touch.current?1:-1);touch.current=null}}><img src={m.src} alt={m.name.replace(/\.[^.]+$/,'')} width={m.width} height={m.height}/><button className="zone prev" aria-label="Previous photograph" onClick={()=>move(-1)}/><button className="zone next" aria-label="Next photograph" onClick={()=>move(1)}/></main><footer>Gibson Chu © {new Date().getFullYear()}</footer></div>{stack.map((p,i)=><section key={p} className={'overlay '+(p==='index'?'index':p==='information'?'information':'project')} style={{zIndex:10+i}} role="dialog" aria-label={pages[p].title} aria-modal={i===stack.length-1} inert={i<stack.length-1?true:undefined} onClick={e=>{if(e.target===e.currentTarget)close();else delegate(e,p)}}><div className="page-content"><Markup html={pages[p].html}/></div></section>)}{zoom&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Photograph viewer" onClick={e=>{if(e.target===e.currentTarget)setZoom(null)}} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(Math.abs(e.changedTouches[0].clientX-touch.current)>30)move(e.changedTouches[0].clientX<touch.current?1:-1)}}><img src={media[zoom.photos[zoom.index]].src} alt={media[zoom.photos[zoom.index]].name}/><button className="viewer-close" aria-label="Close photograph" onClick={()=>setZoom(null)}><svg viewBox="0 0 36 36"><rect width="36" height="36" rx="36"/><path d="M9.3,9.3L18,18l-8.7,8.7 M26.7,9.3L18,18l8.7,8.7"/></svg></button><button className="viewer-prev" aria-label="Previous photograph" onClick={()=>move(-1)}><svg viewBox="0 0 36 36"><rect width="36" height="36" rx="36"/><path d="M22.3,28l-10-10l10-10"/></svg></button><button className="viewer-next" aria-label="Next photograph" onClick={()=>move(1)}><svg viewBox="0 0 36 36"><rect width="36" height="36" rx="36"/><path d="M22.3,28l-10-10l10-10"/></svg></button></div>}</>;
}
