const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=v=>esc(v).replace(/\n/g,'<br />');
const a=(url,label)=>url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:esc(label);
export function renderContent(content,base,seed){const pages={...base.pages},media=content.photos;
 const figure=(id,href,caption)=>{const p=media[id];if(!p)return '';const image=`<img src="${esc(p.src)}" width="${p.width}" height="${p.height}" loading="lazy" alt="${esc(p.alt)}" />`;return `<figure>${href?`<a href="/${esc(href)}">${image}</a>`:`<button class="photo-button" data-photo="${esc(id)}" aria-label="Enlarge photograph">${image}</button>`}${caption?`<figcaption class="caption">${esc(caption)}</figcaption>`:''}</figure>`};
 const header=title=>`<column-set mobile-stack="false" style="--gutter:1rem"><column-unit style="--span:8">${title}</column-unit><column-unit style="--span:4;text-align:right"><a href="#" rel="close-overlay">(Close)</a></column-unit></column-set>`;
 const collections=content.collections.filter(c=>c.published);for(const c of seed.collections)delete pages[c.slug];
 collections.forEach((c,i)=>{const original=seed.collections.find(s=>s.id===c.id);let html;if(original&&['title','description','dates','photoIds'].every(k=>JSON.stringify(c[k])===JSON.stringify(original[k])))html=base.pages[original.slug].html;else html=header(`${String(i+1).padStart(2,'0')} &nbsp; ${esc(c.title)}<br/><br/>`)+figure(c.photoIds[0])+`<br/><br/>${c.description?`<div class="caption">${lines(c.description)}</div><br/>`:''}<gallery-grid style="--columns:2;--gap:.9rem;--mobile-gap:3.3rem">${c.photoIds.slice(1).map(id=>figure(id)).join('')}</gallery-grid><br/><br/><hr/><hr/><br/><br/><column-set style="--gutter:1rem" mobile-stack="false"><column-unit style="--span:6"><span class="caption">(<a href="#" rel="close-overlay">Return to Projects</a>)</span></column-unit><column-unit style="--span:6"><span class="caption">${esc(c.dates)}</span></column-unit></column-set>`;
 html=html.replace(/<img([^>]*?)src="([^"]+)"([^>]*?)alt="[^"]*"/g,(match,before,src,after)=>{const p=Object.values(media).find(p=>p.src===src);return p?`<img${before}src="${src}"${after}alt="${esc(p.alt)}"`:match});
 pages[c.slug]={id:c.id,title:c.title,html,photos:c.photoIds};});
 pages.index={...pages.index,html:header('Index')+`<gallery-grid style="--columns:5;--gap:1rem;--mobile-gap:1rem">${collections.map((c,i)=>figure(c.coverId,c.slug,`${String(i+1).padStart(2,'0')} \u00a0 \u00a0${c.title}`)).join('')}</gallery-grid>`};
 if(JSON.stringify(content.info)!==JSON.stringify(seed.info)){const info=content.info;const originalBio=[...base.pages.information.html.matchAll(/<column-unit[^>]*>([\s\S]*?)<\/column-unit>/g)][2]?.[1];pages.information={...pages.information,html:header('Gibson Chu')+`<br/><column-set style="--gutter:4.1rem"><column-unit style="--span:4">${info.bio===seed.info.bio?originalBio:lines(info.bio)}</column-unit><column-unit style="--span:3">${esc(info.location)}<br/><br/>${a(info.website,info.website.replace(/^https:\/\//,'').replace(/\/$/,''))}<br/>${info.email?`<a href="mailto:${esc(info.email)}">${esc(info.email)}</a>`:''}<br/>${a(info.instagram,'@'+info.instagram.split('/').filter(Boolean).at(-1))}</column-unit><column-unit style="--span:5"><u>Selected Publications</u><br/><br/>${info.publications.map(p=>`${a(p.publisherUrl,p.publisher)}<br/> &nbsp; &gt;&gt; ${a(p.url,p.title)}<br/><br/>`).join('')}</column-unit></column-set>`}}
 pages.homepage={...pages.homepage,photos:content.home};return {pages,media};}
